[package]
name = "backend"
version = "1.0.0"
edition = "2024"

[dependencies]
logging = { path = "../logging" }
blockchain = { path = "../blockchain" }
trade = { path = "../trade" }
arbitrage = { path = "../arbitrage" }
tokio = { workspace = true }
slog = { workspace = true }
